---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: splunk-tile
  type: s3
  source:
    regexp: tiles/splunk.*-(?P<version>.*)\.pivotal
    bucket: {{s3-bucket}}
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: missing-properties
  type: s3
  source:
    bucket: {{s3-bucket}}
    versioned_file: splunk-missing-properties.yml
    access_key_id: {{s3-access-key}}
    secret_access_key: {{s3-secret}}

- name: release-repo
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-community/splunk-firehose-nozzle-release.git

- name: pcf-environment
  type: pool
  source:
    branch: master
    pool: pcf
    private_key: {{pipeline-resource-pool-github-repo-private-key}}
    uri: git@github.com:cf-platform-eng/pipeline-resource-pool-v2

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-hook}}

jobs:
- name: claim-pcf
  plan:
  - aggregate:
    - get: splunk-tile
      trigger: true
    - put: pcf-environment
      params:
        acquire: true

- name: deploy-tile
  plan:
  - aggregate:
    - get: splunk-tile
    - get: pcf-environment
      passed:
      - claim-pcf
      trigger: true
    - get: release-repo
    - get: missing-properties
  - task: run-deploy-tile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cfplatformeng/splunk-ci
      inputs:
      - name: pcf-environment
      - name: splunk-tile
      - name: release-repo
      - name: missing-properties
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-deploy-tile.sh
        args:
          - release-repo
          - splunk-tile
          - pcf-environment
          - missing-properties
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment
        - put: slack-alert
          params:
            icon_emoji: ":robot_face:"
            username: Build pipeline
            channel: "#splunk"
            text: "deploy-tile failed check main pipeline"


- name: test-deploy
  plan:
  - aggregate:
    - get: pcf-environment
      passed:
      - deploy-tile
      trigger: true
    - get: release-repo
  - task: run-deployment-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cfplatformeng/splunk-ci
      inputs:
      - name: pcf-environment
      - name: release-repo
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-test-deploy.sh
        args:
          - release-repo
          - pcf-environment
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment
        - put: slack-alert
          params:
            icon_emoji: ":robot_face:"
            username: Build pipeline
            channel: "#splunk"
            text: "test-deploy failed check main pipeline"


- name: remove-tile
  plan:
  - aggregate:
    - get: release-repo
    - get: pcf-environment
      passed:
        - test-deploy
      trigger: true
  - task: remove-tile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cfplatformeng/splunk-ci
      inputs:
      - name: pcf-environment
      - name: release-repo
      outputs:
      - name: log
      run:
        path: release-repo/ci/run-remove-tile.sh
        args:
          - pcf-environment
    on_failure:
      aggregate:
        - put: pcf-environment
          params:
            release: pcf-environment
        - put: slack-alert
          params:
            icon_emoji: ":robot_face:"
            username: Build pipeline
            channel: "#splunk"
            text: "remove-tile failed check main pipeline"


- name: release-pcf
  plan:
  - get: pcf-environment
    passed:
    - remove-tile
    trigger: true
  - put: pcf-environment
    params:
      release: pcf-environment
